package com.jms.projekt.sql;

public class SQLConstants {

	public static final String GET_ALL_ELEMENTS="SELECT * FROM ELEMENT";
	public static final String GET_ELEMENT_BY_ID="SELECT * FROM ELEMENT WHERE ELEMENT_ID=?";
	public static final String GET_ELEMENT_BY_RANGE="SELECT * FROM ELEMENT WHERE ELEMENT_ID BETWEEN ? AND ?";
	public static final String GET_ELEMENT_BY_NAME="SELECT * FROM ELEMENT WHERE ELEMENT_NAME = ?";
	public static final String ADD_ELEMENT="INSERT INTO ELEMENT (ELEMENT_ID,ELEMENT_NAME,ELEMENT_TYPE,ELEMENT_VALUE,LUD) VALUES (?,?,?,?,CURRENT_TIMESTAMP)";
	public static final String UPDATE_ELEMENT="UPDATE ELEMENT SET ELEMENT_NAME=?,ELEMENT_TYPE=?, ELEMENT_VALUE=?, LUD=CURRENT_TIMESTAMP WHERE ELEMENT_ID=?";
	public static final String DELETE_ELEMENT="DELETE FROM ELEMENT WHERE ELEMENT_ID=?";
}
